----------------------------------------------------------------------
-- object_data.lua
-- Object prototype and spawn definitions
--
-- Expected by object_loader.lua:
--   return {
--     prototypes = { [id] = proto, ... },
--     spawns     = { { proto_id=?, room=? }, ... }
--   }
----------------------------------------------------------------------

--These have changed over time

return {
    prototypes = {
		[0]=   {obj=0,   name="OBJECT 0",                      noun={"OBJECT0"},                              desc="OBJECT0",                                                       value=1,   power=1,  weight=1,     home=0,   respawn={0, 1},               male=true,  plural=false, vowel=false},
		[1]=   {obj=1,   name="brass ring",                    noun={"RING", "BRASS"},                        desc="A solid brass ring lies on the ground, gleaming brightly.",     value=5,   power=0,  weight=5,     home=7,   respawn={186, 396, 235, 29},  male=true,  plural=false, vowel=false},
		[2]=   {obj=2,   name="gold plate",                    noun={"PLATE"},                                desc="A shining gold plate lies before you.",                         value=87,  power=0,  weight=2000,  home=192, respawn=nil,                  male=true,  plural=false, vowel=false},
		[3]=   {obj=3,   name="black vial",                    noun={"BLACK", "VIAL"},                        desc="A small black vial is here.",                                   value=25,  power=0,  weight=150,   home=243, respawn=nil,                  male=true,  plural=false, vowel=false},
		[4]=   {obj=4,   name="finely balanced blade",         noun={"SABRE", "FBB", "BLADE"},                desc="A finely balanced blade glints wickedly here.",                 value=0,   power=30, weight=1000,  home=187, respawn=nil,                  male=true,  plural=false, vowel=false},
		[5]=   {obj=5,   name="jade necklace",                 noun={"NECKLACE", "JADE"},                     desc="There is a fine Jade necklace before you.",                     value=50,  power=0,  weight=500,   home=5,   respawn={539, 75, 571, 416},  male=true,  plural=false, vowel=false},
		[6]=   {obj=6,   name="golden chain",                  noun={"CHAIN", "GOLD"},                        desc="A valuable gold chain is here.",                                value=160, power=0,  weight=500,   home=228, respawn=nil,                  male=true,  plural=false, vowel=false},
		[7]=   {obj=7,   name="Bomb",                          noun={"BOMB", "UXB", "SMALL", "BALL"},         desc="A small ball with a fuse hanging out lies on the ground.",      value=1,   power=1,  weight=2000,  home=5,   respawn={187, 303, 397, 2},   male=true,  plural=false, vowel=false},
		[8]=   {obj=8,   name="gold horseshoe",                noun={"GOLD", "SHOE", "HORSESHOE"},            desc="On the ground nearby lies a fabulous golden horseshoe!",        value=100, power=0,  weight=1000,  home=41,  respawn={328, 46, 418, 160},  male=true,  plural=false, vowel=false},
		[9]=   {obj=9,   name="rough diamond",                 noun={"DIAMOND"},                              desc="A rough, uncut diamond sits on the ground here.",               value=150, power=0,  weight=200,   home=467, respawn=nil,                  male=true,  plural=false, vowel=false},
		[10]=  {obj=10,  name="enraged Terrapin",              noun={"TERRAPIN"},                             desc="An enraged Terrapin crawls about in the dust here.",            value=25,  power=0,  weight=100,   home=21,  respawn=nil,                  male=false, plural=false, vowel=true},
		[11]=  {obj=11,  name="bag of gold coins",             noun={"COINS", "GOLD", "BAG"},                 desc="A small bag of gold coins lies here.",                          value=75,  power=0,  weight=1000,  home=192, respawn=nil,                  male=true,  plural=false, vowel=false},
		[12]=  {obj=12,  name="football",                      noun={"BALL", "FOOTBALL"},                     desc="A large football sits here, waiting to be kicked.",             value=0,   power=0,  weight=10000, home=356, respawn=nil,                  male=true,  plural=false, vowel=false},
		[13]=  {obj=13,  name="ruby",                          noun={"RUBY"},                                 desc="There is a deep red ruby on the floor here.",                   value=100, power=0,  weight=100,   home=428, respawn={109, 741, 449, 453}, male=true,  plural=false, vowel=false},
		[14]=  {obj=14,  name="rusty coin",                    noun={"RUSTY", "COIN"},                        desc="A small rusty coin sits before you.",                           value=10,  power=0,  weight=10,    home=4,   respawn={664, 740, 441, 744}, male=true,  plural=false, vowel=false},
		[15]=  {obj=15,  name="portrait of a princess",        noun={"PORTRAIT"},                             desc="A portrait of a princess catches your eye.",                    value=100, power=0,  weight=2000,  home=431, respawn=nil,                  male=true,  plural=false, vowel=false},
		[16]=  {obj=16,  name="sharp knife",                   noun={"KNIFE"},                                desc="A fine cooking knife has been dropped here.",                   value=0,   power=5,  weight=50,    home=752, respawn=nil,                  male=true,  plural=false, vowel=false},
		[17]=  {obj=17,  name="jewelled clasp",                noun={"CLASP"},                                desc="A jewelled clasp lies here.",                                   value=125, power=0,  weight=100,   home=451, respawn=nil,                  male=true,  plural=false, vowel=false},
		[18]=  {obj=18,  name="mild unassuming rat",           noun={"RAT"},                                  desc="A mild and unassuming rat scurries around your feet.",          value=25,  power=25, weight=100,   home=563, respawn={387, 175, 124, 662}, male=true,  plural=false, vowel=false},
		[19]=  {obj=19,  name="trampette",                     noun={"TRAMPETTE"},                            desc="A heavy looking trampette has been left here.",                 value=0,   power=0,  weight=3260,  home=313, respawn=nil,                  male=true,  plural=false, vowel=false},
		[20]=  {obj=20,  name="shortsword",                    noun={"SHORTSWORD", "SWORD", "SS"},            desc="A worn shortsword lies nearby, the blade dulled with use.",     value=0,   power=30, weight=1100,  home=404, respawn=nil,                  male=true,  plural=false, vowel=false},
		[21]=  {obj=21,  name="slimy creature repellant",      noun={"REPELLANT"},                            desc="A wedge of Ab's Slimy Creature Repellant lies before you.",     value=0,   power=0,  weight=50,    home=191, respawn={93, 330, 423, 15},   male=true,  plural=false, vowel=false},
		[22]=  {obj=22,  name="wooden crucifix",               noun={"CRUCIFIX", "WOODEN"},                   desc="A carved wooden crucifix has been dropped here.",               value=0,   power=0,  weight=50,    home=329, respawn=nil,                  male=true,  plural=false, vowel=false},
		[23]=  {obj=23,  name="glass cross",                   noun={"GLASS", "CROSS"},                       desc="There is an elaborate glass cross here.",                       value=0,   power=0,  weight=200,   home=194, respawn=nil,                  male=true,  plural=false, vowel=false},
		[24]=  {obj=24,  name="ornate key",                    noun={"KEY", "ORNATE"},                        desc="A fine ornate key lies before you.",                            value=0,   power=0,  weight=62,    home=559, respawn=nil,                  male=true,  plural=false, vowel=false},
		[25]=  {obj=25,  name="cleaning rag",                  noun={"RAG", "CLEANING"},                      desc="There is a cleaning and polishing rag on the floor.",           value=0,   power=0,  weight=10,    home=254, respawn={530, 753, 66, 77},   male=true,  plural=false, vowel=false},
		[26]=  {obj=26,  name="gilded canary",                 noun={"CANARY"},                               desc="A gilded canary sits here, looking almost alive.",              value=150, power=0,  weight=550,   home=192, respawn=nil,                  male=true,  plural=false, vowel=false},
		[27]=  {obj=27,  name="stepladder",                    noun={"LADDER", "STEPLADDER"},                 desc="There is a large wooden stepladder here.",                      value=0,   power=0,  weight=1750,  home=535, respawn={513, 537, 494, 489}, male=true,  plural=false, vowel=false},
		[28]=  {obj=28,  name="medallion",                     noun={"MEDALLION"},                            desc="A fancy medallion lies before you.",                            value=60,  power=0,  weight=250,   home=324, respawn=nil,                  male=true,  plural=false, vowel=false},
		[29]=  {obj=29,  name="chalice",                       noun={"CHALICE"},                              desc="There is a chalice here.",                                      value=35,  power=0,  weight=380,   home=327, respawn={522, 419, 321, 495}, male=true,  plural=false, vowel=false},
		[30]=  {obj=30,  name="silver letter opener",          noun={"SILVER"},                               desc="There is a sharp, silver letter opener here.",                  value=35,  power=5,  weight=150,   home=331, respawn=nil,                  male=true,  plural=false, vowel=false},
		[31]=  {obj=31,  name="glass slipper",                 noun={"GLASS", "SLIPPER"},                     desc="A small glass slipper is here, waiting for the correct foot.",  value=20,  power=0,  weight=50,    home=321, respawn={189, 65, 355, 312},  male=true,  plural=false, vowel=false},
		[32]=  {obj=32,  name="Deadly Ninja Throwing Cabbage", noun={"CABBAGE"},                              desc="A peculiarly shaped cabbage lies before you.",                  value=0,   power=18, weight=30,    home=279, respawn=nil,                  male=true,  plural=false, vowel=false},
		[33]=  {obj=33,  name="gold seal",                     noun={"GOLD", "SEAL"},                         desc="A magnificent Gold Seal of State has been discarded here.",     value=175, power=0,  weight=50,    home=451, respawn=nil,                  male=true,  plural=false, vowel=false},
		[34]=  {obj=34,  name="blue potato",                   noun={"BLUE", "POTATO"},                       desc="There is a fresh blue potato here.",                            value=0,   power=0,  weight=50,    home=491, respawn=nil,                  male=true,  plural=false, vowel=false},
		[35]=  {obj=35,  name="pile of chips",                 noun={"CHIPS"},                                desc="There is a pile of greasy but delicious looking chips here.",   value=0,   power=0,  weight=50,    home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		[36]=  {obj=36,  name="blue vial",                     noun={"BLUE", "VIAL"},                         desc="A small blue vial lies temptingly here.",                       value=25,  power=0,  weight=140,   home=357, respawn={324, 234, 224, 805}, male=true,  plural=false, vowel=false},
		[37]=  {obj=37,  name="smooth stone",                  noun={"SMOOTH", "STONE"},                      desc="A smooth stone sits solidly on the floor here.",                value=100, power=15, weight=25,    home=84,  respawn={171, 126, 741, 540}, male=true,  plural=false, vowel=false},
		[38]=  {obj=38,  name="rusty longsword",               noun={"RUSTY", "SWORD", "LS"},                 desc="There is a rusty, but functional, longsword here.",             value=0,   power=30, weight=1000,  home=260, respawn={84, 817, 764, 185},  male=true,  plural=false, vowel=false},
		[39]=  {obj=39,  name="clear vial",                    noun={"CLEAR", "VIAL"},                        desc="A small clear vial lies temptingly here.",                      value=150, power=0,  weight=300,   home=523, respawn=nil,                  male=true,  plural=false, vowel=false},
		[40]=  {obj=40,  name="golden crown",                  noun={"CROWN"},                                desc="Your heart races as you espy a magnificent golden crown!",      value=200, power=0,  weight=1000,  home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		[41]=  {obj=41,  name="brown key",                     noun={"BROWN", "KEY"},                         desc="There is a small, brown key here.",                             value=0,   power=0,  weight=34,    home=222, respawn={402, 88, 221, 79},   male=true,  plural=false, vowel=false},
		[42]=  {obj=42,  name="rocking horse",                 noun={"ROCKING", "HORSE"},                     desc="There is a child's rocking horse here.",                        value=0,   power=0,  weight=1250,  home=540, respawn=nil,                  male=true,  plural=false, vowel=false},
		[43]=  {obj=43,  name="wooden statue",                 noun={"WOODEN", "STATUE"},                     desc="There is a large, indescribably ugly wooden statue here.",      value=75,  power=0,  weight=750,   home=88,  respawn=nil,                  male=true,  plural=false, vowel=false},
		[44]=  {obj=44,  name="ebony rod",                     noun={"ROD", "WAND", "EBONY"},                 desc="An elaborately carved ebony rod lies before you.",              value=10,  power=15, weight=250,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=true},
		[45]=  {obj=45,  name="black pearl",                   noun={"BLACK", "PEARL"},                       desc="A strange, lustrous black pearl has been left here.",           value=150, power=0,  weight=100,   home=479, respawn=nil,                  male=true,  plural=false, vowel=false},
		[46]=  {obj=46,  name="blue crystal",                  noun={"CRYSTAL", "BLUE"},                      desc="A blue crystal rests here, glowing with strange energies.",     value=100, power=0,  weight=100,   home=234, respawn=nil,                  male=true,  plural=false, vowel=false},
		[47]=  {obj=47,  name="pile of bones",                 noun={"BONES", "PILE"},                        desc="An ancient pile of bones lies in a heap here.",                 value=75,  power=0,  weight=995,   home=120, respawn={382, 135, 52, 737},  male=true,  plural=false, vowel=false},
		[48]=  {obj=48,  name="diamond brooch",                noun={"DIAMOND", "BROOCH"},                    desc="You notice a glittering brooch lying at your feet.",            value=125, power=0,  weight=100,   home=110, respawn={113, 67, 570, 496},  male=true,  plural=false, vowel=false},
		[49]=  {obj=49,  name="coil of rope",                  noun={"COIL", "ROPE"},                         desc="A long coil of fine, strong rope lies here.",                   value=0,   power=0,  weight=100,   home=55,  respawn={384, 276, 90, 138},  male=true,  plural=false, vowel=false},
		[50]=  {obj=50,  name="lost chord",                    noun={"LOST", "CHORD"},                        desc="You hear the sound of a lost chord.",                           value=0,   power=0,  weight=25,    home=504, respawn={224, 504, 279, 408}, male=true,  plural=false, vowel=false},
		[51]=  {obj=51,  name="woodsmans Axe",                 noun={"AXE"},                                  desc="A large, sharp woodsmans axe has been left here.",              value=0,   power=20, weight=3000,  home=135, respawn=nil,                  male=true,  plural=false, vowel=false},
		[52]=  {obj=52,  name="golden helmet",                 noun={"HELMET"},                               desc="An ornate, highly decorated golden helmet catchs your eye.",    value=150, power=0,  weight=1000,  home=405, respawn=nil,                  male=true,  plural=false, vowel=false},
		[53]=  {obj=53,  name="golden acorn",                  noun={"GOLD", "ACORN"},                        desc="A glint of light from a golden acorn catches your eye.",        value=60,  power=0,  weight=100,   home=144, respawn={88, 124, 143, 417},  male=true,  plural=false, vowel=false},
		[54]=  {obj=54,  name="trinket",                       noun={"TRINKET"},                              desc="An unidentifiable but not unvaluable trinket gleams brightly.", value=150, power=0,  weight=205,   home=185, respawn=nil,                  male=true,  plural=false, vowel=false},
		[55]=  {obj=55,  name="pewter goblet",                 noun={"PEWTER", "GOBLET"},                     desc="A sadly empty pewter goblet is here,",                          value=15,  power=0,  weight=100,   home=187, respawn=nil,                  male=true,  plural=false, vowel=false},
		[56]=  {obj=56,  name="delicate ice crystal",          noun={"ICE", "CRYSTAL"},                       desc="A delicate ice crystal glistens nearby.",                       value=50,  power=5,  weight=50,    home=383, respawn=nil,                  male=true,  plural=false, vowel=false},
		[57]=  {obj=57,  name="pendant",                       noun={"PENDANT"},                              desc="There is a pendant here.",                                      value=37,  power=0,  weight=150,   home=184, respawn=nil,                  male=true,  plural=false, vowel=false},
		[58]=  {obj=58,  name="champagne cork",                noun={"CORK"},                                 desc="A champagne cork lies here, no bottle unfortunately.",          value=25,  power=0,  weight=3,     home=538, respawn=nil,                  male=true,  plural=false, vowel=false},
		[59]=  {obj=59,  name="jewelled Egg",                  noun={"EGG"},                                  desc="There is a fabulously jewelled egg here.",                      value=75,  power=0,  weight=85,    home=184, respawn=nil,                  male=true,  plural=false, vowel=false},
		[60]=  {obj=60,  name="brass key",                     noun={"BRASS", "KEY"},                         desc="There is a large, brass key lying here.",                       value=2,   power=0,  weight=200,   home=45,  respawn={135, 545, 19, 357},  male=true,  plural=false, vowel=false},
		[61]=  {obj=61,  name="bronze key",                    noun={"BRONZE", "KEY"},                        desc="There is a bronze key here.",                                   value=0,   power=0,  weight=20,    home=145, respawn={328, 509, 422, 223}, male=true,  plural=false, vowel=false},
		[62]=  {obj=62,  name="book of poems by Milo D Milo",  noun={"BOOK"},                                 desc="Milo D. Milo's Book of Poetry lies before you.",                value=75,  power=0,  weight=200,   home=279, respawn=nil,                  male=true,  plural=false, vowel=false},
		[63]=  {obj=63,  name="figurine",                      noun={"FIGURINE"},                             desc="There is a finely carved figurine here.",                       value=100, power=0,  weight=100,   home=540, respawn=nil,                  male=true,  plural=false, vowel=false},
		[64]=  {obj=64,  name="dusty cloak",                   noun={"CLOAK", "DUSTY"},                       desc="A dark, dusty cloak lies on the ground.",                       value=108, power=0,  weight=500,   home=167, respawn={258, 731, 188, 538}, male=true,  plural=false, vowel=false},
		[65]=  {obj=65,  name="Bomb",                          noun={"BOMB", "XB", "SMALL", "BALL"},          desc="A small ball with a fuse hanging out lies on the ground.",      value=125, power=0,  weight=2000,  home=172, respawn={2, 397, 303, 187},   male=true,  plural=false, vowel=false},
		[66]=  {obj=66,  name="quicklime pellet",              noun={"PELLET", "QUICKLIME"},                  desc="A small pellet of quicklime lies here.",                        value=0,   power=0,  weight=100,   home=191, respawn=nil,                  male=true,  plural=false, vowel=false},
		[67]=  {obj=67,  name="platinum key",                  noun={"PLATINUM", "KEY"},                      desc="There is a shiny key here, apparently made from platinum.",     value=60,  power=0,  weight=30,    home=65,  respawn={816, 763, 730, 248}, male=true,  plural=false, vowel=false},
		[68]=  {obj=68,  name="burnished key",                 noun={"BURNISHED", "KEY"},                     desc="A burnished key lies before you.",                              value=0,   power=0,  weight=20,    home=123, respawn={730, 174, 513, 234}, male=true,  plural=false, vowel=false},
		[69]=  {obj=69,  name="steel key",                     noun={"STEEL", "KEY"},                         desc="There is a steel key on the ground.",                           value=0,   power=0,  weight=25,    home=95,  respawn={357, 154, 81, 220},  male=true,  plural=false, vowel=false},
		[70]=  {obj=70,  name="corroded key",                  noun={"CORRODED", "KEY"},                      desc="There is a highly corroded (but still usable) key here.",       value=0,   power=0,  weight=15,    home=18,  respawn={371, 95, 84, 222},   male=true,  plural=false, vowel=false},
		[71]=  {obj=71,  name="crystal of jet and gold",       noun={"CRYSTAL"},                              desc="A fine crystal of darkest Jet, shot with gold, lies here.",     value=160, power=0,  weight=275,   home=800, respawn=nil,                  male=true,  plural=false, vowel=false},
		[72]=  {obj=72,  name="lead bar",                      noun={"BAR", "LEAD"},                          desc="A large lead bar lies on the floor here.",                      value=125, power=5,  weight=3500,  home=191, respawn=nil,                  male=true,  plural=false, vowel=false},
		[73]=  {obj=73,  name="sceptre",                       noun={"SCEPTRE"},                              desc="There is a sceptre here.",                                      value=37,  power=0,  weight=1200,  home=507, respawn=nil,                  male=true,  plural=false, vowel=false},
		[74]=  {obj=74,  name="brick",                         noun={"ROCK", "BRICK"},                        desc="There is a large square brick here.",                           value=0,   power=10, weight=2000,  home=180, respawn={171, 110, 86, 329},  male=true,  plural=false, vowel=false},
		[75]=  {obj=75,  name="necklace made of teeth",        noun={"NECKLACE"},                             desc="There is a rough necklace here, made out of old teeth.",        value=100, power=10, weight=1000,  home=387, respawn=nil,                  male=true,  plural=false, vowel=false},
		[76]=  {obj=76,  name="dark gemstone",                 noun={"DARK", "GEMSTONE"},                     desc="Lying before you is a dark gemstone of strange beauty.",        value=35,  power=0,  weight=25,    home=784, respawn=nil,                  male=true,  plural=false, vowel=false},
		[77]=  {obj=77,  name="bone",                          noun={"BONE"},                                 desc="Some flies buzz around a horribly fresh looking bone.",         value=150, power=0,  weight=600,   home=400, respawn=nil,                  male=true,  plural=false, vowel=false},
		[78]=  {obj=78,  name="unicorns horn",                 noun={"HORN"},                                 desc="A brightly coloured unicorns horn lies before you.",            value=50,  power=5,  weight=100,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=true},
		[79]=  {obj=79,  name="ripe apple",                    noun={"RIPE", "APPLE"},                        desc="A fine, ripe apple has been dropped here.",                     value=5,   power=0,  weight=2500,  home=123, respawn={186, 47, 495, 327},  male=true,  plural=false, vowel=false},
		[80]=  {obj=80,  name="gold apple",                    noun={"GOLD", "APPLE"},                        desc="There is a large, gold apple here.",                            value=75,  power=0,  weight=2499,  home=192, respawn=nil,                  male=true,  plural=false, vowel=false},
		[81]=  {obj=81,  name="red rose",                      noun={"RED", "ROSE"},                          desc="A beautiful red rose fills the air with a heavenly scent.",     value=0,   power=0,  weight=10,    home=67,  respawn={511, 65, 145, 326},  male=true,  plural=false, vowel=false},
		[82]=  {obj=82,  name="sovereign",                     noun={"SOVEREIGN"},                            desc="There is a sovereign here.",                                    value=80,  power=0,  weight=30,    home=192, respawn=nil,                  male=true,  plural=false, vowel=false},
		[83]=  {obj=83,  name="shield",                        noun={"SHIELD"},                               desc="There's a useful looking shield here, dented but serviceable.", value=100, power=5,  weight=1500,  home=408, respawn=nil,                  male=true,  plural=false, vowel=false},
		[84]=  {obj=84,  name="gold brick",                    noun={"GOLD", "BRICK"},                        desc="Somehow an ordinary gold brick has been dropped here.",         value=160, power=0,  weight=1400,  home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		[85]=  {obj=85,  name="bracelet",                      noun={"BRACELET"},                             desc="There is a fancy bracelet here.",                               value=38,  power=0,  weight=50,    home=532, respawn={118, 73, 243, 48},   male=true,  plural=false, vowel=false},
		[86]=  {obj=86,  name="gold fish",                     noun={"GOLD", "FISH"},                         desc="A small, gold fish lies on the floor before you.",              value=125, power=0,  weight=250,   home=192, respawn=nil,                  male=true,  plural=false, vowel=false},
		[87]=  {obj=87,  name="empty glass",                   noun={"EMPTY", "GLASS"},                       desc="There is an ordinary, empty drinking glass here.",              value=0,   power=0,  weight=127,   home=330, respawn=nil,                  male=true,  plural=false, vowel=true},
		[88]=  {obj=88,  name="drinking cup",                  noun={"CUP"},                                  desc="There is a drinking cup here.",                                 value=58,  power=0,  weight=250,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		[89]=  {obj=89,  name="mayors chain",                  noun={"CHAIN", "MAYORS"},                      desc="A large, elaborate mayors chain lies here.",                    value=25,  power=15, weight=1100,  home=529, respawn=nil,                  male=true,  plural=false, vowel=false},
		[90]=  {obj=90,  name="mace",                          noun={"MACE"},                                 desc="There is a mace here.",                                         value=20,  power=0,  weight=250,   home=505, respawn=nil,                  male=true,  plural=false, vowel=false},
		[91]=  {obj=91,  name="toy tiara",                     noun={"TOY", "TIARA"},                         desc="A tiara lies here, shining with paste diamonds.",               value=63,  power=0,  weight=400,   home=55,  respawn=nil,                  male=true,  plural=false, vowel=false},
		[92]=  {obj=92,  name="gold disk",                     noun={"GOLD", "DISK"},                         desc="Strangely, there's a discarded gold tiddlywink here!",          value=63,  power=0,  weight=500,   home=61,  respawn=nil,                  male=true,  plural=false, vowel=false},
		[93]=  {obj=93,  name="pink bracelet",                 noun={"TOY", "PINK", "BRACELET"},              desc="A small pink childs bracelet has been dropped here.",           value=63,  power=0,  weight=505,   home=3,   respawn=nil,                  male=true,  plural=false, vowel=false},
		[94]=  {obj=94,  name="cardboard crown",               noun={"TOY", "CARDBOARD", "CROWN"},            desc="Nearby lies a cardboard crown, for kids who would be king.",    value=63,  power=0,  weight=500,   home=5,   respawn=nil,                  male=true,  plural=false, vowel=false},
		[95]=  {obj=95,  name="statue",                        noun={"METAL", "STATUE"},                      desc="A statue made from strange unidentifiable metal stands here.",  value=80,  power=0,  weight=500,   home=730, respawn=nil,                  male=true,  plural=false, vowel=false},
		[96]=  {obj=96,  name="Hermit's hoard",                noun={"HOARD"},                                desc="A hoard of fabulous jewels and metals catches your gaze.",      value=350, power=0,  weight=3000,  home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		[97]=  {obj=97,  name="junior longsword",              noun={"JLS", "SWORD", "TOY"},                  desc="A junior longsword (for minors only) has been dropped here.",   value=63,  power=20, weight=1550,  home=41,  respawn=nil,                  male=true,  plural=false, vowel=false},
		[98]=  {obj=98,  name="wood key",                      noun={"WOOD", "KEY"},                          desc="You happen to notice a small, rather nondescript wood key.",    value=0,   power=0,  weight=5,     home=372, respawn=nil,                  male=true,  plural=false, vowel=false},
		[99]=  {obj=99,  name="sprig of mistletoe",            noun={"MISTLETOE", "SPRIG"},                   desc="There is a small sprig of mistletoe here.",                     value=0,   power=0,  weight=50,    home=57,  respawn=nil,                  male=true,  plural=false, vowel=false},
		[100]= {obj=100, name="bejewelled dagger",             noun={"DAGGER"},                               desc="A fabulously bejewelled dagger lies before you.",               value=125, power=15, weight=100,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		[101]= {obj=101, name="ivory dagger",                  noun={"DAGGER", "IVORY"},                      desc="An ivory handled dagger lies before you.",                      value=125, power=15, weight=100,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=true},
		[102]= {obj=102, name="jet dagger",                    noun={"DAGGER", "JET"},                        desc="A dagger of darkest jet lies before you.",                      value=125, power=15, weight=100,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		[103]= {obj=103, name="flint dagger",                  noun={"DAGGER", "FLINT"},                      desc="An ancient flint dagger lies before you.",                      value=125, power=15, weight=100,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		[104]= {obj=104, name="tiepin",                        noun={"TIEPIN", "V1", "VO", "VOBJ1"},          desc="A very old coin lies on the ground",                            value=10,  power=0,  weight=100,   home=69,  respawn=nil,                  male=true,  plural=false, vowel=false},
		[105]= {obj=105, name="ornamental frog",               noun={"FROG", "V2", "VO", "VOBJ2"},            desc="A large Snowman winks at you and says \"Hi\"",                  value=50,  power=0,  weight=100,   home=22,  respawn=nil,                  male=true,  plural=false, vowel=false},
		[106]= {obj=106, name="fiery orb",                     noun={"FIERY", "ORB", "V3", "VO", "VOBJ3"},    desc="You see a beautiful Mist Maiden by the path",                   value=100, power=0,  weight=100,   home=419, respawn=nil,                  male=true,  plural=false, vowel=false},
		[107]= {obj=107, name="silver spike",                  noun={"SILVER", "SPIKE", "V4", "VO", "VOBJ4"}, desc="There is a mysterious looking black bladed sword here",         value=25,  power=15, weight=100,   home=571, respawn=nil,                  male=true,  plural=false, vowel=false},
		[108]= {obj=108, name="placebo",                       noun={"PLACEBO"},                              desc="There is a placebo here.",                                      value=0,   power=0,  weight=1,     home=144, respawn=nil,                  male=true,  plural=false, vowel=false},
		[109]= {obj=109, name="silver spoon",                  noun={"SILVER", "SPOON"},                      desc="An old silver spoon lies before you.",                          value=80,  power=0,  weight=175,   home=662, respawn=nil,                  male=true,  plural=false, vowel=false},
		[110]= {obj=110, name="rusty key",                     noun={"RUSTY", "KEY"},                         desc="There is a rusty key sitting here on the ground.",              value=0,   power=0,  weight=200,   home=171, respawn=nil,                  male=true,  plural=false, vowel=false},
		[111]= {obj=111, name="amber clasp",                   noun={"AMBER", "CLASP"},                       desc="There is a beautiful amber clasp here.",                        value=100, power=0,  weight=300,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=true},
		[112]= {obj=112, name="cheap trinket",                 noun={"CHEAP", "TRINKET"},                     desc="The dull glitter of a cheap trinket catches your eye.",         value=15,  power=0,  weight=150,   home=661, respawn=nil,                  male=true,  plural=false, vowel=false},
		[113]= {obj=113, name="ivory bookmark",                noun={"IVORY", "BOOKMARK"},                    desc="There is a worn but still valuable bookmark here.",             value=75,  power=0,  weight=250,   home=nil, respawn=nil,                  male=true,  plural=false, vowel=false},
		},

	spawns = { -- reproduces the home field of the above
		{proto_id=0,   room=0},   
		{proto_id=1,   room=7},   
		{proto_id=2,   room=192}, 
		{proto_id=3,   room=243}, 
		{proto_id=4,   room=187}, 
		{proto_id=5,   room=5},   
		{proto_id=6,   room=228}, 
		{proto_id=7,   room=5},   
		{proto_id=8,   room=41},  
		{proto_id=9,   room=467}, 
		{proto_id=10,  room=21},  
		{proto_id=11,  room=192}, 
		{proto_id=12,  room=356}, 
		{proto_id=13,  room=428}, 
		{proto_id=14,  room=4},   
		{proto_id=15,  room=431}, 
		{proto_id=16,  room=752}, 
		{proto_id=17,  room=451}, 
		{proto_id=18,  room=563}, 
		{proto_id=19,  room=313}, 
		{proto_id=20,  room=404}, 
		{proto_id=21,  room=191}, 
		{proto_id=22,  room=329}, 
		{proto_id=23,  room=194}, 
		{proto_id=24,  room=559}, 
		{proto_id=25,  room=254}, 
		{proto_id=26,  room=192}, 
		{proto_id=27,  room=535}, 
		{proto_id=28,  room=324}, 
		{proto_id=29,  room=327}, 
		{proto_id=30,  room=331}, 
		{proto_id=31,  room=321}, 
		{proto_id=32,  room=279}, 
		{proto_id=33,  room=451}, 
		{proto_id=34,  room=491}, 
		{proto_id=35,  room=nil}, 
		{proto_id=36,  room=357}, 
		{proto_id=37,  room=84},  
		{proto_id=38,  room=260}, 
		{proto_id=39,  room=523}, 
		{proto_id=40,  room=nil}, 
		{proto_id=41,  room=222}, 
		{proto_id=42,  room=540}, 
		{proto_id=43,  room=88},  
		{proto_id=44,  room=nil}, 
		{proto_id=45,  room=479}, 
		{proto_id=46,  room=234}, 
		{proto_id=47,  room=120}, 
		{proto_id=48,  room=110}, 
		{proto_id=49,  room=55},  
		{proto_id=50,  room=504}, 
		{proto_id=51,  room=135}, 
		{proto_id=52,  room=405}, 
		{proto_id=53,  room=144}, 
		{proto_id=54,  room=185}, 
		{proto_id=55,  room=187}, 
		{proto_id=56,  room=383}, 
		{proto_id=57,  room=184}, 
		{proto_id=58,  room=538}, 
		{proto_id=59,  room=184}, 
		{proto_id=60,  room=45},  
		{proto_id=61,  room=145}, 
		{proto_id=62,  room=279}, 
		{proto_id=63,  room=540}, 
		{proto_id=64,  room=167}, 
		{proto_id=65,  room=172}, 
		{proto_id=66,  room=191}, 
		{proto_id=67,  room=65},  
		{proto_id=68,  room=123}, 
		{proto_id=69,  room=95},  
		{proto_id=70,  room=18},  
		{proto_id=71,  room=800}, 
		{proto_id=72,  room=191}, 
		{proto_id=73,  room=507}, 
		{proto_id=74,  room=180}, 
		{proto_id=75,  room=387}, 
		{proto_id=76,  room=784}, 
		{proto_id=77,  room=400}, 
		{proto_id=78,  room=nil}, 
		{proto_id=79,  room=123}, 
		{proto_id=80,  room=192}, 
		{proto_id=81,  room=67},  
		{proto_id=82,  room=192}, 
		{proto_id=83,  room=408}, 
		{proto_id=84,  room=nil}, 
		{proto_id=85,  room=532}, 
		{proto_id=86,  room=192}, 
		{proto_id=87,  room=330}, 
		{proto_id=88,  room=nil}, 
		{proto_id=89,  room=529}, 
		{proto_id=90,  room=505}, 
		{proto_id=91,  room=55},  
		{proto_id=92,  room=61},  
		{proto_id=93,  room=3},   
		{proto_id=94,  room=5},   
		{proto_id=95,  room=730}, 
		{proto_id=96,  room=nil}, 
		{proto_id=97,  room=41},  
		{proto_id=98,  room=372}, 
		{proto_id=99,  room=57},  
		{proto_id=100, room=nil}, 
		{proto_id=101, room=nil}, 
		{proto_id=102, room=nil}, 
		{proto_id=103, room=nil}, 
		{proto_id=104, room=69},  
		{proto_id=105, room=22},  
		{proto_id=106, room=419}, 
		{proto_id=107, room=571}, 
		{proto_id=108, room=144}, 
		{proto_id=109, room=662}, 
		{proto_id=110, room=171}, 
		{proto_id=111, room=nil}, 
		{proto_id=112, room=661}, 
		{proto_id=113, room=nil}, 
	}
}
